# Generated by Django 2.0.7 on 2018-08-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keytag', models.CharField(max_length=100)),
                ('keyname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
