# Generated by Django 2.0.7 on 2018-08-08 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keystate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checkout', models.DateField()),
                ('user_checkout', models.CharField(max_length=100)),
                ('state_checkout', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='key',
            name='keystate_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='keyhistory',
            name='keytag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keystate.Key'),
        ),
    ]
