# Generated by Django 2.0.7 on 2018-08-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keystate', '0003_auto_20180808_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='curr_user',
            field=models.CharField(default='aymen', max_length=60),
        ),
        migrations.AlterField(
            model_name='keyhistory',
            name='keytag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keystate.Key'),
        ),
    ]
