# Generated by Django 2.0.7 on 2018-08-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keystate', '0004_auto_20180808_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyhistory',
            name='keytag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keystate.Key'),
        ),
    ]
